[versions]
kotlin = "2.2.20"
ksp = "2.2.20-2.0.4"
agp = "8.9.1"
materialVersion = "1.10.2"
minSdk = "24"
compileSdk = "36"
targetSdk = "36"
gmsPlayServices = "18.5.0"
hmsCore = "6.6.0.300"
hmsInstaller = "6.6.0.300"
coreKtx = "1.17.0"
activityCompose = "1.12.3"
lifecycle = "2.10.0"
materialIconsCore = "1.7.8"
navigationCompose = "2.9.7"
composeBom = "2026.01.01"
material3 = "1.4.0"
hilt = "2.57.2"
hiltNavigationCompose = "1.3.0"
retrofit = "3.0.0"
okhttp = "5.3.2"
gson = "2.13.2"
coil = "2.7.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
mockitoCore = "5.14.1"
mockitoKotlin = "5.4.0"
coroutinesTest = "1.9.0"
coroutines = "1.9.0"
javaxInject = "1"
appcompat = "1.7.1"
material = "1.13.0"
truth = "1.4.5"
mockk = "1.13.13"

[libraries]
androidx-compose-material-icons-core = { module = "androidx.compose.material:material-icons-core", version.ref = "materialIconsCore" }
androidx-compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "materialIconsCore" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-android-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }
okhttp-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutinesTest" }
javax-inject = { group = "javax.inject", name = "javax.inject", version.ref = "javaxInject" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
mockito-core = { group = "org.mockito", name = "mockito-core", version.ref = "mockitoCore" }
mockito-kotlin = { group = "org.mockito.kotlin", name = "mockito-kotlin", version.ref = "mockitoKotlin" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
hms-core = { group = "com.huawei.hms", name = "base", version.ref = "hmsCore" }
gms-play-services = { group = "com.google.android.gms", name = "play-services-base", version.ref = "gmsPlayServices" }
hms-installer = { group = "com.huawei.hms", name = "hmscoreinstaller", version.ref = "hmsInstaller" }
hilt-android-testing = { group = "com.google.dagger", name = "hilt-android-testing", version.ref = "hilt" }
google-truth = { group = "com.google.truth", name = "truth", version.ref = "truth" }
mockk-android = { group = "io.mockk", name = "mockk-android", version.ref = "mockk" }
mockk-agent = { group = "io.mockk", name = "mockk", version.ref = "mockk" }

[bundles]
compose = [
    "androidx-activity-compose",
    "androidx-compose-ui",
    "androidx-compose-ui-graphics",
    "androidx-compose-ui-tooling-preview",
    "androidx-compose-material3",
    "androidx-navigation-compose"
]

lifecycle = [
    "androidx-lifecycle-runtime-ktx",
    "androidx-lifecycle-viewmodel-compose",
    "androidx-lifecycle-runtime-compose"
]

network = [
    "retrofit",
    "retrofit-converter-gson",
    "okhttp-logging-interceptor",
    "gson"
]

coroutines = [
    "kotlinx-coroutines-core"
]

hilt = [
    "hilt-android",
    "hilt-navigation-compose"
]

testing = [
    "junit",
    "androidx-junit",
    "androidx-espresso-core",
    "mockito-core",
    "mockito-kotlin",
    "kotlinx-coroutines-test",
    "google-truth",
    "mockk-android",
    "mockk-agent"
]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
android-library = { id = "com.android.library", version.ref = "agp" }